/*
 * Stub definitions for ROM symbols.
 * Normally generated by romgen during MIDP's ROMImage build step,
 * but the CLDC release library was built without ROMization, so
 * these symbols are not present in libcldc_vm_r.a / libcldc_vm_g.a.
 * Since the MIDP build uses USE_CLDC_RELEASE=true and the symbols
 * are still referenced, we provide empty stubs here.
 */

extern "C" {
const int _rom_task_mirrors_size = 0;
const int _rom_task_mirrors[] = {0};
const int _rom_task_mirrors_bitmap[] = {0};
}
