/*
 * BuildFlags_vita.hpp - PS Vita compile-time configuration options
 *
 * This file is automatically generated - do not edit manually.
 */

#ifndef BUILD_FLAGS_VITA_HPP
#define BUILD_FLAGS_VITA_HPP

// Socket support: Vita uses newlib BSD socket API
#define USE_BSD_SOCKET 1
#define LINUX 1

// Timer: Vita does not support signal-based timer interrupts
// Timer thread support is controlled by build config (default: disabled)
#define SUPPORTS_TIMER_INTERRUPT 0
#define SUPPORTS_TIMER_THREAD 1

// Other Vita-specific flags
#define VITA_PLATFORM 1

#endif /* BUILD_FLAGS_VITA_HPP */
