# GenVersion.cmake - generate vita_version.h at build time.
# Version = APP_VER (manual, from VITA_VERSION) + build number (git commit
# count of the samples repo) + short hash, so every installed VPK can be
# told apart on device and in logs.
# Rewrites the header only when its content actually changes, to avoid
# rebuilding dependents on every no-op build.

set(usage "cmake -DVERSION_FILE=<out.h> -DSRC_DIR=<dir> -DAPP_VER=01.00 -DAPP_NAME=Name -P GenVersion.cmake")

if(NOT VERSION_FILE OR NOT SRC_DIR OR NOT APP_VER OR NOT APP_NAME)
    message(FATAL_ERROR ${usage})
endif()

set(GIT_COUNT "")
set(GIT_HASH "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SRC_DIR} rev-list --count HEAD
        OUTPUT_VARIABLE GIT_COUNT OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE rc1)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C ${SRC_DIR} rev-parse --short HEAD
        OUTPUT_VARIABLE GIT_HASH OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE rc2)
    if(NOT rc1 EQUAL 0 OR GIT_COUNT STREQUAL "")
        set(GIT_COUNT 0)
    endif()
    if(NOT rc2 EQUAL 0 OR GIT_HASH STREQUAL "")
        set(GIT_HASH "unknown")
    endif()
endif()

set(content "/* AUTO-GENERATED by GenVersion.cmake - do not edit */
#define VITA_PORT_APP_NAME \"${APP_NAME}\"
#define VITA_PORT_APP_VER \"${APP_VER}\"
#define VITA_PORT_BUILD ${GIT_COUNT}
#define VITA_PORT_HASH \"${GIT_HASH}\"
#define VITA_PORT_VERSION_STRING \"${APP_NAME} v${APP_VER} b${GIT_COUNT} (${GIT_HASH})\"
#define HELLO_JAR_SIZE ${HELLO_JAR_SIZE}
")

if(EXISTS ${VERSION_FILE})
    file(READ ${VERSION_FILE} old)
    if(old STREQUAL content)
        return()
    endif()
endif()
file(WRITE ${VERSION_FILE} ${content})
